int INTAKE_SERVO_ANGLE = 30;
int SCORE_SERVO_ANGLE = 150;
int DEFAULT_SERVO_ANGLE = 90;

/* AUTO CONSTANTS */

float DRIVE_FORWARD_POWER = 1.0;
float TURN_FORWARD_POWER = 1.0;
float TURN_BACKWARD_POWER = -0.5;

/* END AUTO CONSTANTS */

long SCORE_TIME = 500; // ms